name: arknights_analysis
description: An application can help you collect game data more easily via
  offcial api of HyperGryph.

publish_to: none

version: 0.1.6+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  another_flushbar: 1.12.30
  badges: 3.1.2
  bot_toast: 4.1.3
  collection: 1.17.2
  connectivity_plus: 5.0.1
  dartx: 1.2.0
  dartz: 0.10.1
  data_table_2: 2.5.8
  dio: 5.3.3
  drift: 2.13.0
  easy_localization: 3.0.3
  ffi: 2.1.0
  file_picker: 6.0.0
  fluent_ui: 4.7.7
  flutter:
    sdk: flutter
  flutter_riverpod: 2.4.5
  flutter_screenutil: 5.9.0
  font_awesome_flutter: 10.6.0
  freezed_annotation: 2.4.1
  go_router: 12.1.0
  intl: 0.18.1
  json_annotation: 4.8.1
  logger: 2.0.2+1
  modal_bottom_sheet: 3.0.0-pre
  package_info_plus: 4.2.0
  path: 1.8.3
  path_provider: 2.1.1
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.3
  riverpod_annotation: 2.3.0
  shared_preferences: 2.2.2
  sqlite3_flutter_libs: 0.5.18
  time: 2.1.3
  url_launcher: 6.2.1
  webview_windows: 0.2.1
  win32: 5.0.9
  window_manager: 0.3.7

dev_dependencies:
  build_runner: 2.4.6
  build_verify: 3.1.0
  custom_lint: 0.5.6
  drift_dev: 2.13.1
  flutter_gen_runner: 5.3.2
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  go_router_builder: 2.3.4
  json_serializable: 6.7.1
  lint: 2.1.2
  retrofit_generator: 8.0.3
  riverpod_generator: 2.3.3
  riverpod_lint: 2.1.1

flutter_gen:
  output: lib/core/gen

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      - assets/translations/*

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true

  fonts:
    - family: SourceHanSC
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.ttf
          weight: 400
        - asset: fonts/SourceHanSansCN-Bold.ttf
          weight: 700

  assets:
    - assets/dependencies/
    - assets/images/
    - assets/translations/
