name: arknights_analysis
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  another_flushbar: 1.10.29
  bot_toast: 4.0.2
  dartx: 1.1.0
  dartz: 0.10.1
  dio: 4.0.6
  drift: 1.6.0
  fluent_ui: 3.12.0
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.4
  flutter_screenutil: 5.5.3+2
  freezed_annotation: 2.0.3
  go_router: 3.1.1
  json_annotation: 4.5.0
  logger: 1.1.0
  path: 1.8.2
  path_provider: 2.0.10
  pretty_dio_logger: 1.2.0-beta-1
  retrofit: 3.0.1+1
  riverpod: 1.0.3
  sqlite3_flutter_libs: 0.5.7
  webview_windows: 0.1.9
  window_manager: 0.2.5

dev_dependencies:
  build_runner: 2.1.11
  drift_dev: 1.6.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.0.3+1
  json_serializable: 6.2.0
  msix: 3.6.2
  retrofit_generator: 4.0.1

dependency_overrides:
  path: 1.8.2

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: fonts/NotoSansSC-Regular.otf
        - asset: fonts/NotoSansSC-Bold.otf
          weight: 700

  assets:
    - assets/icons/
    - assets/images/

msix_config:
  display_name: Arknights Analysis
  publisher_display_name: MasterHiei
  identity_name: club.kimomiya.arknights-analysis
  capabilities: internetClient
