name: arknights_analysis
description: An application can help you collect game data more easily via
  offcial api of HyperGryph.

publish_to: none

version: 0.1.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  another_flushbar: 1.12.30
  badges: 3.1.1
  bot_toast: 4.0.4
  collection: 1.17.1
  connectivity_plus: 4.0.1
  dartx: 1.1.0
  dartz: 0.10.1
  data_table_2: 2.5.2
  dio: 5.2.0+1
  drift: 2.8.2
  easy_localization: 3.0.2
  ffi: 2.0.2
  file_picker: 5.3.2
  fluent_ui: 4.6.2
  flutter:
    sdk: flutter
  flutter_riverpod: 2.3.6
  flutter_screenutil: 5.8.4
  font_awesome_flutter: 10.4.0
  freezed_annotation: 2.2.0
  go_router: 8.0.1
  intl: 0.18.0
  json_annotation: 4.8.1
  logger: 1.4.0
  modal_bottom_sheet: 3.0.0-pre
  package_info_plus: 4.0.2
  path: 1.8.3
  path_provider: 2.0.15
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1
  shared_preferences: 2.1.2
  sqlite3_flutter_libs: 0.5.15
  time: 2.1.3
  url_launcher: 6.1.11
  webview_windows: 0.2.1
  win32: 5.0.3
  window_manager: 0.3.4

dev_dependencies:
  build_runner: 2.4.5
  build_verify: 3.1.0
  custom_lint: 0.4.0
  drift_dev: 2.8.3
  flutter_gen_runner: 5.3.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  go_router_builder: 2.1.1
  json_serializable: 6.7.0
  lint: 2.1.2
  retrofit_generator: 7.0.1
  riverpod_lint: 1.3.2

flutter_gen:
  output: lib/core/gen

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      - assets/translations/*

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true

  fonts:
    - family: SourceHanSC
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.ttf
          weight: 400
        - asset: fonts/SourceHanSansCN-Bold.ttf
          weight: 700

  assets:
    - assets/dependencies/
    - assets/images/
    - assets/translations/
