name: arknights_analysis
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dartz: 0.10.1
  dio: 4.0.6
  file_picker: 4.5.1
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.4
  flutter_screenutil: 5.5.3+1
  freezed_annotation: 2.0.3
  go_router: 3.1.0
  isar: 2.5.0
  isar_flutter_libs: 2.5.0
  json_annotation: 4.5.0
  logger: 1.1.0
  path_provider: 2.0.10
  riverpod: 1.0.3
  url_launcher: 6.1.2
  window_manager: 0.2.3

dev_dependencies:
  build_runner: 2.1.11
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.0.3+1
  isar_generator: 2.5.0
  json_serializable: 6.2.0

flutter:
  uses-material-design: true
