name: arknights_analysis
description: An application can help you collect game data more easily via
  offcial api of HyperGryph.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  another_flushbar: 1.12.29
  badges: 2.0.3
  bot_toast: 4.0.3
  collection: 1.16.0
  connectivity_plus: 3.0.2
  dartx: 1.1.0
  dartz: 0.10.1
  data_table_2: 2.3.7
  dio: 4.0.6
  drift: 2.2.0
  easy_localization: 3.0.1
  file_picker: 5.2.2
  fl_chart: 0.55.2
  fluent_ui: 4.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: 2.0.2
  flutter_screenutil: 5.5.4
  font_awesome_flutter: 10.2.1
  freezed_annotation: 2.2.0
  go_router: 5.1.1
  intl: 0.17.0
  json_annotation: 4.7.0
  logger: 1.1.0
  modal_bottom_sheet: 2.1.2
  package_info_plus: 3.0.1
  path: 1.8.2
  path_provider: 2.0.11
  pretty_dio_logger: 1.2.0-beta-1
  retrofit: 3.3.1
  riverpod: 2.0.2
  shared_preferences: 2.0.15
  sqlite3_flutter_libs: 0.5.10
  time: 2.1.3
  url_launcher: 6.1.6
  webview_windows: 0.2.1
  window_manager: 0.2.7

dev_dependencies:
  build_runner: 2.3.2
  drift_dev: 2.2.0+1
  flutter_test:
    sdk: flutter
  freezed: 2.2.0
  json_serializable: 6.5.3
  lint: 1.10.0
  retrofit_generator: 4.2.0

flutter:
  uses-material-design: true

  fonts:
    - family: SourceHanSC
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.ttf
          weight: 400
        - asset: fonts/SourceHanSansCN-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/translations/
