name: arknights_analysis
description: An application can help you collect game data more easily via
  offcial api of HyperGryph.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  another_flushbar: 1.12.29
  badges: 3.0.3
  bot_toast: 4.0.3
  collection: 1.17.0
  connectivity_plus: 3.0.3
  dartx: 1.1.0
  dartz: 0.10.1
  data_table_2: 2.4.1
  dio: 5.1.1
  drift: 2.6.0
  easy_localization: 3.0.1
  ffi: 2.0.1
  file_picker: 5.2.6
  fl_chart: 0.61.0
  fluent_ui: 4.4.2
  flutter:
    sdk: flutter
  flutter_riverpod: 2.3.2
  flutter_screenutil: 5.7.0
  font_awesome_flutter: 10.4.0
  freezed_annotation: 2.2.0
  go_router: 6.5.2
  intl: 0.17.0
  json_annotation: 4.8.0
  logger: 1.3.0
  modal_bottom_sheet: 3.0.0-pre
  package_info_plus: 3.0.3
  path: 1.8.2
  path_provider: 2.0.14
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1
  shared_preferences: 2.1.0
  sqlite3_flutter_libs: 0.5.13
  time: 2.1.3
  url_launcher: 6.1.10
  webview_windows: 0.2.1
  win32: 3.1.3
  window_manager: 0.3.1

dev_dependencies:
  build_runner: 2.3.3
  custom_lint: 0.3.2
  drift_dev: 2.6.0
  flutter_gen_runner: 5.2.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  json_serializable: 6.6.1
  lint: 2.0.1
  retrofit_generator: 6.0.0+1
  riverpod_lint: 1.1.6

flutter_gen:
  output: lib/core/gen

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true

  fonts:
    - family: SourceHanSC
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.ttf
          weight: 400
        - asset: fonts/SourceHanSansCN-Bold.ttf
          weight: 700

  assets:
    - assets/dependencies/
    - assets/images/
    - assets/translations/
