name: arknights_analysis
description: An application can help you collect game data more easily via
  official api of HyperGryph.

publish_to: none

version: 0.1.10+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  another_flushbar: 1.12.30
  badges: 3.1.2
  bot_toast: 4.1.3
  collection: 1.18.0
  connectivity_plus: 6.0.5
  dartx: 1.2.0
  data_table_2: 2.5.15
  dio: 5.7.0
  drift: 2.20.0
  easy_localization: 3.0.7
  ffi: 2.1.3
  file_picker: 8.1.2
  fluent_ui: 4.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_screenutil: 5.9.3
  font_awesome_flutter: 10.7.0
  fpdart: 1.1.0
  freezed_annotation: 2.4.4
  go_router: 14.2.7
  intl: 0.19.0
  json_annotation: 4.9.0
  logger: 2.4.0
  modal_bottom_sheet: 3.0.0
  package_info_plus: 8.0.2
  path: 1.9.0
  path_provider: 2.1.4
  pretty_dio_logger: 1.4.0
  retrofit: 4.4.0
  riverpod_annotation: 2.3.5
  shared_preferences: 2.3.2
  sqlite3_flutter_libs: 0.5.24
  time: 2.1.4
  url_launcher: 6.3.0
  webview_windows: 0.4.0
  win32: 5.5.4
  window_manager: 0.4.2

dev_dependencies:
  build_runner: 2.4.12
  build_verify: 3.1.0
  custom_lint: 0.6.5
  drift_dev: 2.20.1
  flutter_gen_runner: 5.7.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  go_router_builder: 2.7.1
  json_serializable: 6.8.0
  lint: 2.3.0
  retrofit_generator: 9.1.0
  riverpod_generator: 2.4.3
  riverpod_lint: 2.3.13

flutter_gen:
  output: lib/core/gen

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false
      style: dot-delimiter
    exclude:
      - assets/translations/*

  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter:
  uses-material-design: true

  fonts:
    - family: SourceHanSC
      fonts:
        - asset: fonts/SourceHanSansCN-Regular.ttf
          weight: 400
        - asset: fonts/SourceHanSansCN-Bold.ttf
          weight: 700

  assets:
    - assets/dependencies/
    - assets/images/
    - assets/translations/
